### ISSUE TITLE
Wrong version for pmatch

### ISSUE THREAD

**Issue by ralf-krause** [moodleou/moodle-qtype_varnumunit#6]
Hi Tim,
I found that I must change the version string for match inside the version.php. The latest version of patch is 2018080800 and not 2018081300.
`'qtype_pmatch'        => 2018080800,`
Best regards, Ralf

**Comment by timhunt** [comment]
Doh! copy-paste error. Thank you for catching it so quickly. Should be fixed now.

Also, I created https://tracker.moodle.org/browse/MDL-63129.
